apiVersion: v1
kind: Pod
metadata:
  name: guest-app-pod
  labels:
    name: guest-app-pod
    app: guest-book-app

spec:
  containers:
    - name: guest-app
      image: kubernetes/guestbook:v2
      ports:
      - containerPort: 80