apiVersion: v1
kind: Service
metadata:
  name: guest-app-service
  labels:
    name: guest-app-service
    app: guest-book-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80

  selector:
    name: guest-app-pod
    app: guest-book-app