apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-webapp-deployment
  labels:
    app: guest-book-app

spec:
  replicas: 2
  selector:
    matchLabels:
      name: guest-app-pod
      app: guest-book-app

  template:
    metadata:
      name: guest-app-pod
      labels:
        name: guest-app-pod
        app: guest-book-app

    spec:
      containers:
        - name: guest-app
          image: kubernetes/guestbook:v2
          ports:
            - containerPort: 80
