apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: guest-redis-pod
    app: guest-book-app
spec:
  ports:
    - port: 6379
      targetPort: 6379

  selector:
    name: guest-redis-pod
    app: guest-book-app