apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-guest-deployment
  labels:
    app: guest-book-app

spec:
  replicas: 2

  selector:
    matchLabels:
      name: guest-redis-pod
      app: guest-book-app

  template:
    metadata:
      name: guest-redis-pod
      labels:
        name: guest-redis-pod
        app: guest-book-app

    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379