apiVersion: v1
kind: Pod
metadata:
  name: guest-redis-pod
  labels:
    name: guest-redis-pod
    app: guest-book-app

spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379